### ISSUE TITLE
A comment in style produces an error

### ISSUE THREAD

**Issue by XenTerSeO** [styled-components/babel-plugin-styled-components#115]
const HeaderUser = styled.a`
      font-size: 0;
      width: 42px;
      height: 42px;
      flex-shrink: 0;
      &:hover {
        border: 0;
        margin-top: -10px;
        padding-top: 7px;
        border-top: 3px solid rgb(255, 255, 255);

        /* ${HeaderAvatar} {
          border: 2px solid rgb(255, 255, 255);
        } */
      }
    `

=>

    ERROR in ./client/components/header.jsx
    Module build failed: TypeError: /xen/client/components/header.jsx: Property value expected type of string but got null
        at Object.validate (/xen/node_modules/babel-types/lib/definitions/index.js:161:13)
        at validate (/xen/node_modules/babel-types/lib/index.js:505:9)
        at Object.builder (/xen/node_modules/babel-types/lib/index.js:466:7)
        at /xen/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js:26:16
        at Array.map (<anonymous>)
        at exports.default (/xen/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js:25:43)
        at exports.default (/xen/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/index.js:25:29)
        at PluginPass.TaggedTemplateExpression (/xen/node_modules/babel-plugin-styled-components/lib/index.js:21:40)
        at newFn (/xen/node_modules/babel-traverse/lib/visitors.js:276:21)
        at NodePath._call (/xen/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call (/xen/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit (/xen/node_modules/babel-traverse/lib/path/context.js:105:12)
        at TraversalContext.visitQueue (/xen/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/xen/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/xen/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node (/xen/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit (/xen/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue (/xen/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitMultiple (/xen/node_modules/babel-traverse/lib/context.js:103:17)
        at TraversalContext.visit (/xen/node_modules/babel-traverse/lib/context.js:190:19)
        at Function.traverse.node (/xen/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit (/xen/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue (/xen/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitMultiple (/xen/node_modules/babel-traverse/lib/context.js:103:17)
        at TraversalContext.visit (/xen/node_modules/babel-traverse/lib/context.js:190:19)
        at Function.traverse.node (/xen/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit (/xen/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue (/xen/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/xen/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/xen/node_modules/babel-traverse/lib/context.js:192:19)
    @ multi ./client/components/header.jsx

**Comment by philpl** [comment]
This has been a longer standing issue as it removes the interpolation without joining the surrounding strings, if I’m not mistaken 😬

PRs welcome, but this hasn’t been a high priority before

**Comment by quantizor** [comment]
Hi @XenTerSeO, this is the same family as #103: block comment containing an interpolation crashed the templateLiterals/transpile.js path. Verified the shape from your repro produces valid output on current main.

Closing. Please open a fresh issue if anything similar comes up on 2.3.0+.
