### ISSUE TITLE
Escaped unicode within `css` causes compiling error

### ISSUE THREAD

**Issue by good-idea** [styled-components/babel-plugin-styled-components#215]
This code:

```
export const P = styled.p`
	${({ theme, align }) => css`
		&:after {
			content: '\00a0\00a0';
		}
	`};
`
```

(other styles in this component have been omitted)

Produces this error during compilation:

```
ERROR in ./src/app/Components/Type.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Property value expected type of string but got null
    at Object.validate (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at validate (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteral (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/types/lib/builders/generated/index.js:335:31)
    at /Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js:29:18
    at Array.map (<anonymous>)
    at /Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/transpile.js:28:10
    at /Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/index.js:17:33
    at PluginPass.TaggedTemplateExpression (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/babel-plugin-styled-components/lib/index.js:41:42)
    at newFn (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:124:21)
    at TraversalContext.visitSingle (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/joseph/Sites/hikawa.studio/app-deploy-test/node_modules/@babel/traverse/lib/context.js:90:19)
 @ ./src/app/Views/Cart/CartModal.js 6:0-66 47:101-108 58:88-95 63:36-43
 @ ./src/app/Views/Kame.js
 @ ./src/app/App.js
 @ ./src/app/index.js
 @ multi ./src/app/index.js
```

If I remove the `css`, it produces a more helpful error:

```
ERROR in ./src/app/Components/Type.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/joseph/Sites/hikawa.studio/app-deploy-test/src/app/Components/Type.js: Invalid escape sequence in template (84:19)

  82 |  ${({ theme, align }) => `
  83 |          &:after {
> 84 |                  content: '\00a0\00a0';
     |                                     ^
  85 |          }
  86 |  `};
  87 | `
```

I have successfully compiled all of this before. A fresh install (with no lock file) fails on the build. I can poke around the lock file for the working build if that's helpful.

<details>
  <summary>babel config</summary>

  	```
	const path = require('path')
	
	const forBrowser = process.env.WEBPACK
	
	module.exports = {
		presets: [
			[
				'@babel/preset-env',
				{
					targets:
						forBrowser === 'webpack'
							? {
									browsers: ['last 2 versions'],
							  }
							: {
									node: 'current',
							  },
				},
			],
			'@babel/preset-react',
			'@babel/preset-flow',
		],
		env: {
			development: {
				plugins: ['flow-react-proptypes', 'react-hot-loader/babel'],
			},
		},
		plugins: [
			'import-graphql',
			'@loadable/babel-plugin',
			'flow-react-proptypes',
			forBrowser ? false : 'dynamic-import-node',
			[
				'babel-plugin-module-resolver',
				{
					extensions: ['.js', '.web.js', '.native.js'],
					alias: {
						Components: './src/app/Components',
						Views: './src/app/Views',
						Types: './src/app/Types',
						Utils: './src/app/Utils',
						GraphQL: './src/app/GraphQL',
						Services: './src/app/Services',
					},
					cwd: 'babelrc',
				},
			],
			['babel-plugin-styled-components', { ssr: true, minify: false }],
			'@babel/plugin-proposal-class-properties',
			'@babel/plugin-proposal-object-rest-spread',
			'@babel/plugin-syntax-dynamic-import',
			'@babel/plugin-syntax-export-default-from',
			'ramda',
		].filter(Boolean),
	}
	```  
</details>

**Comment by good-idea** [comment]
As an aside, I have this extra `css` in there because it get syntax highlighting to work in VS Code.

Other than this issue - are there any problems with using `css` like this?

**Comment by rtymchyk** [comment]
If need a workaround, you can use `\u00A0` instead.

**Comment by quantizor** [comment]
Hi @good-idea, thanks for the report and the helpful "if I remove the css helper" diagnostic. That pointed at the right spot.

Verified locally with your repro shape: escaped-unicode escape sequences (`\00a0`, etc.) inside a `css` block now produce valid output, e.g.

  styled.div`::before { content: "\00a0"; }`
    -> styled.div.withConfig({...})(["::before{content:\"\\00a0\";}"])

Closing as resolved.
