### ISSUE TITLE
TypeError: Cannot read property 'a' of undefined (when running next build)

### ISSUE THREAD

**Issue by cullophid** [styled-components/babel-plugin-styled-components#296]
When Running next build I get an error if the styled-components plugin is enabled:

```
Creating an optimized production build  

Compiled successfully.


> Build error occurred
TypeError: Cannot read property 'a' of undefined
    at Object.C (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:15104:85)
    at Object.3h+p (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:656:60)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.LJdJ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:15171:21)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.P+uG (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:17244:15)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Module.i6+/ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:22419:83)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.0 (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:342:18) {
  type: 'TypeError'
}
Automatically optimizing pages .npm ERR! code ELIFECYCLE
```
```
"babel-plugin-styled-components": "1.11.1",
"styled-components": "5.1.1",
"next": "9.5.1",
```

ts-config:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["ES2015", "ES2019", "ES2020", "DOM"],
    "module": "CommonJS",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es6",
    "paths": {
      "cylindo-ui": ["src/components/cylindo-ui@next"],
      "src": ["src"],
      "api-src": ["api-src"]
    },
    "noEmit": true
  },
  "include": ["src", "api", "api-src/src"],
  "exclude": ["./node_modules", "api-src/node_modules"]
}
```

.bablerc
```
{
  "presets": ["next/babel"],
  "plugins": [["babel-plugin-styled-components", { "ssr": true }]]
}
```

**Comment by kitten** [comment]
This is likely caused by an issue with CommonJS interior which is a common problem.

Given your `tsconfig` you're transpiling your code to CommonJS which isn't necessary. (`"module": "commonjs"`)

Instead you may want to set `"module": "es2015"`

**Comment by cullophid** [comment]
No unfortunately that does not make a difference (though there was no reason why it was set to commonJS).
Im not 100% sure its an issue with this plugin, but it only happens when the plugin is used.
