### ISSUE TITLE
Styled component displayName won't show up in React Dev Tools

### ISSUE THREAD

**Issue by lumio** [styled-components/babel-plugin-styled-components#57]
Hello,

I followed the instructions in the README file and created a .babelrc, refer the styled-components plugin, but the names are not shown.

```json
{
   "plugins": [ "styled-components" ],
   "presets": [ "react-app" ]
}
```

I know it reads my .babelrc file, because when I leave out the presets, I get a bunch of error messages.

When I inspect my styled-components I can also see the prefix `sc-`. So that seems to work.
Another interesting behavior occurs when I try to set displayName true:

```json
{
   "plugins": ["styled-components", {
      "displayName": true
    }],
   "presets": [ "react-app" ]
}
```

Then I get the following error:
```
yarn start v0.23.4
$ babel-node scripts/start.js
/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/plugin.js:131
      throw new Error(messages.get("pluginInvalidProperty", loc, i, key));
      ^

Error: Plugin 1 specified in "/Users/.../.babelrc" provided an invalid property of "displayName"
    at Plugin.init (/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/.../node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/.../node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/.../node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/..../node_modules/babel-register/lib/node.js:154:7)
error Command failed with exit code 1.
```

I'm using TypeScript 2.3.2, my setup is based on react-scripts but with webpack 2.6.1

Thanks 😀

**Comment by huy-nguyen** [comment]
I think this is related to #41. This is one solution that worked for me while using typescript 2.3: https://github.com/styled-components/babel-plugin-styled-components/issues/41#issuecomment-297535321. After switching to 2.4, the problem seems to go away for me: https://github.com/styled-components/babel-plugin-styled-components/issues/41#issuecomment-310201410

**Comment by justim** [comment]
Maybe this is already fixed for @lumio, but the problem seems to be that the `.babelrc` is invalid. The `styled-components` entry should be a single entry in the `plugins` entry.

```json
{
   "plugins": [
      ["styled-components", {
         "displayName": true
      }]
   ],
   "presets": [ "react-app" ]
}
```

**Comment by lumio** [comment]
@justim thanks. Just a small mistake I haven't seen.
I'm using another plugin though for typescript now that works just fine
