### ISSUE TITLE
Module build failed after update from 1.1.4 to 1.1.5

### ISSUE THREAD

**Issue by cncolder** [styled-components/babel-plugin-styled-components#61]
I understand this Error throw from another module. Maybe stylis or maybe styled-jsx.

But 1.1.5 is a patch semver update. It introduce a break change.

I downgrade to 1.1.4. It no problem.

```bash
Module build failed: Error: /pages/room.js?entry: Nesting detected at 11:34. Unfortunately nesting is not supported by styled-jsx.
    at Function.disableNestingPlugin (/node_modules/styled-jsx/dist/lib/style-transform.js:19:13)
    at proxy (/node_modules/stylis/stylis.js:1133:30)
    at compile (/node_modules/stylis/stylis.js:679:10)
    at compile (/node_modules/stylis/stylis.js:319:17)
    at stylis (/node_modules/stylis/stylis.js:1270:16)
    at preprocessHelper (/node_modules/babel-plugin-styled-components/lib/css/preprocessUtils.js:95:43)
    at exports.default (/node_modules/babel-plugin-styled-components/lib/css/preprocess.js:12:96)
    at exports.default (/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/preprocess.js:48:41)
    at exports.default (/node_modules/babel-plugin-styled-components/lib/visitors/templateLiterals/index.js:23:30)
    at PluginPass.TaggedTemplateExpression (/node_modules/babel-plugin-styled-components/lib/index.js:21:40)
    at newFn (/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/node_modules/babel-traverse/lib/index.js:114:17)
```

My code used styled-components

```jsx
const StyledGrid = styled(Grid)`
  .am-flexbox .am-flexbox-item .am-grid-item-content .am-grid-item-inner-content .am-grid-icon {
    width: 33%;
    height: 33%;
  }
`

const ListCenterItem = styled(List.Item)`
  .am-list-line .am-list-content {
    text-align: center;
  }
`

const ListCenterLargeItem = styled(ListCenterItem)`
  .am-list-line .am-list-content {
    font-size: .5rem;
  }
`

const ShareQRCode = styled(Result)`
  .am-result-pic {
    width: auto;
    height: auto;
    margin: 0;
    line-height: inherit;
    background-size: auto auto;
  }
`
```

My babel setting

```json
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "import",
            [
                {
                    "libraryName": "antd-mobile"
                },
                {
                    "libraryName": "recompose",
                    "libraryDirectory": "",
                    "camel2DashComponentName": false
                }
            ]
        ],
        [
            "styled-components",
            {
                "ssr": true,
                "displayName": true,
                "preprocess": true
            }
        ]
    ]
}
```

**Comment by philpl** [comment]
I've seen this before and I'm not quite sure why it's happening but it's somehow related to `styled-jsx`.

Can you try to turn the `preprocess` option off? It might cause conflicts with the styled-jsx plugin. I haven't raised an issue on next.js yet, since I'm not sure what's causing this.

But on the other hand, `preprocess` is experimental and if it's what's causing the incompatibility, you should just leave it off for now.

**Comment by philpl** [comment]
Duplicate of #934

**Comment by cncolder** [comment]
It's not duplicate.

babel-plugin-styled-components@1.1.4 dep stylis@2
babel-plugin-styled-components@1.1.5 dep stylis@3

stylis has release a major version.

So I think we need publish as babel-plugin-styled-components@2.0.0

**Comment by philpl** [comment]
@cncolder 1.1.5 upgrade to stylis 3, but stylis is **only used for experimental preprocesing**.

Apart from that, if the same bug manifests in two different versions, it's still the same bug :wink:
